platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated = File.expand_path('Flutter/Generated.xcconfig', File.dirname(__FILE__))
  unless File.exist?(generated)
    raise "#{generated} must exist. Run flutter pub get first"
  end
  File.foreach(generated) do |line|
    if (m = line.match(/FLUTTER_ROOT=(.*)/))
      return m[1].strip
    end
  end
  raise "FLUTTER_ROOT not found in #{generated}"
end

puts "Flutter root: #{flutter_root}"
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

