name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install Flutter dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Clean & install CocoaPods
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..

      - name: Build iOS without code signing
        run: flutter build ios --no-codesign

      - name: Archive app using xcodebuild
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath ${{ github.workspace }}/build/Runner.xcarchive archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/build/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath ${{ github.workspace }}/build/Runner.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/Runner.ipa
