name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # or any version >=3.32.4 that you want

      - name: Install dependencies
        run: flutter pub get

      - name: Generate iOS build files
        run: flutter build ios --no-codesign

      - name: Build IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath ${{ github.workspace }}/build/Runner.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/build/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath ${{ github.workspace }}/build/Runner.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/Runner.ipa