name: Build iOS IPA

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install Flutter dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Clean & prep iOS build
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..

      - name: Build IPA
        run: flutter build ipa --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
