name: Generate iOS Folder

on:
  workflow_dispatch: # So you can run it manually

jobs:
  generate-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' # Change if needed

      - name: Install dependencies
        run: flutter pub get

      - name: Create iOS folder
        run: flutter create .

      - name: Upload ios/ folder
        uses: actions/upload-artifact@v3
        with:
          name: ios-folder
          path: ios/