name: Generate iOS Folder

on:
  workflow_dispatch:

jobs:
  generate-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'  # or any version >=3.32.4 that you want

      - name: Install dependencies
        run: flutter pub get

      - name: Create iOS folder
        run: flutter create .

      - name: Upload ios/ folder
        uses: actions/upload-artifact@v4
        with:
          name: ios-folder
          path: ios/
