name: Check Flutter SDK Path

on:
  workflow_dispatch:  # Allows you to manually run this from the GitHub Actions tab

jobs:
  check_flutter_path:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Show Flutter version and SDK location
        run: |
          echo "Flutter version:"
          flutter --version
          echo "Flutter SDK root (machine-readable):"
          flutter --version --machine